### ISSUE TITLE
Rotating AVIF images makes them corrupt and unreadable

### ISSUE THREAD

**Issue by bsduck** [nomacs/nomacs#620]
Using the rotate feature in nomacs on an AVIF image corrupts the file. This is dangerous!

You just need to press the R key to end up with a wasted image that neither nomacs nor avifdec will be able to read anymore. No matter whether you rotate it back to its original state directly after. Once the nomacs window is closed, you cannot open that file again.

nomacs error message:
`[WARNING] [Basic Loader] could not load /my/image.avif`

avifdec error message:
`ERROR: Failed to decode image: BMFF parsing failed`

System info:
· FreeBSD 12.2
· nomacs 3.16
· libavif 0.8.4
· qt-avif-image-plugin 0.4.1

**Comment by novomesk** [comment]
Can you try to build from master? It it possible that it was fixed meanwhile.
I use following build on Windows and there is no problem with rotating:
![nomacs](https://user-images.githubusercontent.com/52529860/111318450-5e7cfb00-8665-11eb-8f1f-252d4e43f103.png)

**Comment by bsduck** [comment]
I just built nomacs from master but the problem persists with this version.

![nomacs-build-info](https://user-images.githubusercontent.com/54958509/111712355-bfffbe00-884d-11eb-802b-8c9554a98a16.png)

**Comment by scrubbbbs** [comment]
exiv2 doesn't have write support for AVIF, this appears to work correctly when using kimageformats-plugins, which will be the preferred method going forward.

**Comment by scrubbbbs** [comment]
We do not auto-save after rotation anymore and also do not support lossless rotation of AVIF so this is no longer a problem. After rotating AVIF you will get a prompt to recompress the image.

Update: It seems we can now support lossless rotation for some later versions of kimageformat-plugins and/or exiv2 and certain AVIF files (see images in formats-testset/AVIF)
